# Generated by Django 5.2.8 on 2026-07-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
